ALTER TABLE DB_CHANNELS 
ADD CONSTRAINT PK_CHANNEL_ID PRIMARY KEY (CHANNEL_ID) 

ALTER TABLE DB_PRODUCTS 
ADD CONSTRAINT PK_PROD_ID PRIMARY KEY (PROD_ID) 
 

ALTER TABLE DB_PROMOTIONS 
ADD CONSTRAINT PK_PROMO_ID PRIMARY KEY (PROMO_ID) 

ALTER TABLE DB_COUNTRY 
ADD CONSTRAINT PK_COUNTRY_ID PRIMARY KEY (COUNTRY_ID) 


ALTER TABLE DB_CUSTOMERS 
ADD CONSTRAINT PK_CUST_ID PRIMARY KEY (CUST_ID) 
  
ALTER TABLE DB_CUSTOMERS 
ADD FOREIGN KEY (COUNTRY_ID) REFERENCES DB_COUNTRY (COUNTRY_ID) 
 
ALTER TABLE DB_CUSTOMERS 
ADD CONSTRAINT ckGender CHECK(CUST_GENDER= 'M' OR CUST_GENDER= 'F' OR CUST_GENDER= 'O' )

SELECT * FROM DB_CUSTOMERS


ALTER TABLE DB_SALES
ADD CONSTRAINT PK_SALESTRANS_ID PRIMARY KEY (SALESTRANS_ID) 
  
ALTER TABLE DB_SALES 
ADD FOREIGN KEY (PROD_ID) REFERENCES DB_PRODUCTS (PROD_ID) 
  
ALTER TABLE DB_SALES
ADD FOREIGN KEY (CUST_ID) REFERENCES DB_CUSTOMERS (CUST_ID) 
  
ALTER TABLE DB_SALES 
ADD FOREIGN KEY (CHANNEL_ID) REFERENCES DB_CHANNELS (CHANNEL_ID) 
  
ALTER TABLE DB_SALES 
ADD FOREIGN KEY (PROMO_ID) REFERENCES DB_PROMOTIONS (PROMO_ID) 
