CREATE TABLE DB_CHANNELS 
(CHANNEL_ID INT NOT NULL, 
CHANNEL_DESC VARCHAR(20) NOT NULL, 
CHANNEL_CLASS VARCHAR(20)) 

CREATE TABLE DB_PRODUCTS 
(PROD_ID INT NOT NULL, 
PROD_NAME VARCHAR(50) NOT NULL, 
PROD_DESC VARCHAR(4000) NOT NULL, 
PROD_LIST_PRICE DECIMAL(8,2) NOT NULL, 
PROD_CATEGORY VARCHAR(50) NOT NULL, 
PROD_SUBCATEGORY VARCHAR(50) NOT NULL,
SUPPLIER_ID INT NOT NULL,
PROD_STATUS VARCHAR(20),
) 
  

CREATE TABLE DB_PROMOTIONS 
(PROMO_ID INT NOT NULL, 
PROMO_NAME VARCHAR(30) NOT NULL, 
PROMO_SUBCATEGORY VARCHAR(30) NOT NULL, 
PROMO_CATEGORY VARCHAR(30) NOT NULL, 
PROMO_COST NUMERIC NOT NULL, 
PROMO_BEGIN_DATE DATE NOT NULL, 
PROMO_END_DATE DATE NOT NULL) 


CREATE TABLE DB_COUNTRY 
(COUNTRY_ID INT NOT NULL, 
COUNTRY_NAME VARCHAR(50), 
COUNTRY_SUBREGION VARCHAR(30), 
COUNTRY_REGION VARCHAR(20)) 


CREATE TABLE DB_CUSTOMERS 
(CUST_ID INT NOT NULL, 
CUST_FIRST_NAME VARCHAR(20), 
CUST_LAST_NAME VARCHAR(40), 
CUST_GENDER CHAR(1), 
CUST_YEAR_OF_BIRTH DECIMAL(20,0), 
CUST_MARITAL_STATUS VARCHAR(20), 
CUST_INCOME_LEVEL VARCHAR(30), 
CUST_CREDIT_LIMIT DECIMAL(20,2), 
CUST_MAIN_PHONE_NUMBER VARCHAR(25), 
CUST_EMAIL VARCHAR(30), 
CUST_STREET_ADDRESS VARCHAR(40), 
CUST_POSTAL_CODE VARCHAR(10), 
CUST_STATE_PROVINCE VARCHAR(40), 
CUST_CITY VARCHAR(30), 
COUNTRY_ID INT, 
) 
CREATE TABLE DB_SALES 
(SALESTRANS_ID INT NOT NULL, 
PROD_ID INT NOT NULL,
CUST_ID INT, 
CHANNEL_ID INT NOT NULL, 
PROMO_ID INT NOT NULL, 
SALE_DATE DATE, 
SHIPPING_DATE DATE, 
PAYMENT_DATE DATE, 
QUANTITY_SOLD INT, 
UNIT_PRICE INT, 
AMOUNT_SOLD INT) 

DROP TABLE DB_CUSTOMERS
DROP TABLE DB_COUNTRY