INSERT INTO DB_CHANNELS (CHANNEL_ID, CHANNEL_DESC, CHANNEL_CLASS) 
SELECT DISTINCT CHANNEL_ID, CHANNEL_DESC, CHANNEL_CLASS FROM [LIY26].[dbo].[LI_CHANNELS] 

INSERT INTO DB_PRODUCTS (PROD_ID, PROD_NAME, PROD_DESC, PROD_LIST_PRICE, PROD_CATEGORY, PROD_SUBCATEGORY,SUPPLIER_ID, PROD_STATUS ) 
SELECT DISTINCT PROD_ID, PROD_NAME, PROD_DESC, PROD_LIST_PRICE, PROD_CATEGORY, PROD_SUBCATEGORY ,SUPPLIER_ID, PROD_STATUS
FROM [LIY26].[dbo].[LI_PRODUCTS] 

INSERT INTO DB_PROMOTIONS (PROMO_ID, PROMO_NAME,PROMO_SUBCATEGORY, 
PROMO_CATEGORY, PROMO_COST, PROMO_BEGIN_DATE, PROMO_END_DATE) 
SELECT DISTINCT PROMO_ID, PROMO_NAME ,PROMO_SUBCATEGORY, PROMO_CATEGORY, 
PROMO_COST, PROMO_BEGIN_DATE, PROMO_END_DATE 
FROM [LIY26].[dbo].[LI_PROMOTIONS] 

INSERT INTO DB_COUNTRY (COUNTRY_ID, COUNTRY_NAME, COUNTRY_SUBREGION, COUNTRY_REGION) 
SELECT DISTINCT COUNTRY_ID, COUNTRY_NAME, COUNTRY_SUBREGION, COUNTRY_REGION 
FROM [LIY26].[dbo].[LI_CUSTOMERS_INTX] 



INSERT INTO DB_CUSTOMERS 
SELECT N.CUST_ID, N.CUST_FIRST_NAME, N.CUST_LAST_NAME, N.CUST_GENDER, E.CUST_YEAR_OF_BIRTH,E.CUST_MARITAL_STATUS,E.CUST_INCOME_LEVEL, E.CUST_CREDIT_LIMIT,N.CUST_MAIN_PHONE_NUMBER, N.CUST_EMAIL, N.CUST_STREET_ADDRESS,N.CUST_POSTAL_CODE, N.CUST_STATE_PROVINCE,
N.CUST_CITY, N.COUNTRY_ID  
FROM [LIY26].[dbo].[LI_CUSTOMERS_INTX] AS N 
JOIN [LIY26].[dbo].[LI_CUSTOMERS_EXT] AS E ON N.CUST_ID=E.CUST_ID 

INSERT INTO DB_SALES (SALESTRANS_ID, PROD_ID, CUST_ID, CHANNEL_ID, PROMO_ID, 
SALE_DATE, SHIPPING_DATE, PAYMENT_DATE, QUANTITY_SOLD, UNIT_PRICE, AMOUNT_SOLD) 
SELECT DISTINCT SALESTRANS_ID, PROD_ID, CUST_ID, CHANNEL_ID, PROMO_ID, 
SALE_DATE, SHIPPING_DATE, PAYMENT_DATE, QUANTITY_SOLD, UNIT_PRICE, AMOUNT_SOLD 
FROM [LIY26].[dbo].[LI_SALES_12_13] 


INSERT INTO DB_SALES (SALESTRANS_ID, PROD_ID, CUST_ID, CHANNEL_ID, PROMO_ID, 
SALE_DATE, SHIPPING_DATE, PAYMENT_DATE, QUANTITY_SOLD, UNIT_PRICE, AMOUNT_SOLD) 
SELECT DISTINCT SALESTRANS_ID, PROD_ID, CUST_ID, CHANNEL_ID, PROMO_ID, 
SALE_DATE, SHIPPING_DATE, PAYMENT_DATE, QUANTITY_SOLD, UNIT_PRICE, AMOUNT_SOLD 
FROM [LIY26].[dbo].[LI_SALES_14] 
