--BV01

SELECT 
P.PROD_ID, P.PROD_NAME, P.PROD_LIST_PRICE, P.PROD_SUBCATEGORY, P.PROD_CATEGORY, PR.PROMO_ID, PR.PROMO_NAME, PR.PROMO_SUBCATEGORY, PR.PROMO_CATEGORY, PR.PROMO_COST, PR.PROMO_BEGIN_DATE, PR.PROMO_END_DATE, S.QUANTITY_SOLD, S.AMOUNT_SOLD,  
CAST(AVG(P.PROD_LIST_PRICE) AS DECIMAL (8,2)) AS AVERAGE_PRODUCT_PRICE, 
CAST(AVG(S.QUANTITY_SOLD) AS DECIMAL (8,2)) AS AVERAGE_QUANTITY_SOLD,  
CAST(AVG(S.AMOUNT_SOLD) AS DECIMAL (8,2)) AS AVERAGE_AMOUNT_SOLD 
 
FROM 
LI_PRODUCTS P, LI_PROMOTIONS PR, LI_SALES_12_13_14 S 
  
WHERE 
S.PROD_ID = P.PROD_ID AND S.PROMO_ID = PR.PROMO_ID 
  
GROUP BY 
P.PROD_ID, P.PROD_NAME, P.PROD_LIST_PRICE, P.PROD_SUBCATEGORY, P.PROD_CATEGORY, PR.PROMO_ID, PR.PROMO_NAME, PR.PROMO_SUBCATEGORY, PR.PROMO_CATEGORY, PR.PROMO_COST, PR.PROMO_BEGIN_DATE, PR.PROMO_END_DATE, S.QUANTITY_SOLD, S.AMOUNT_SOLD,  
CAST(AVG(P.PROD_LIST_PRICE) AS DECIMAL (8,2), 
CAST(AVG(S.QUANTITY_SOLD) AS DECIMAL (8,2)),  
CAST(AVG(S.AMOUNT_SOLD) AS DECIMAL (8,2)) 
  
ORDER BY 
P.PROD_ID DESC, PR.PROMO_ID DESC 



--BV02

SELECT 
CI.CUST_ID, CI.CUST_FIRST_NAME+' '+CI.CUST_LAST_NAME AS FULL_NAME, CI.CUST_MAIN_PHONE_NUMBER, 
CI.CUST_EMAIL, CI.CUST_POSTAL_CODE, P.PROD_ID AS PROD_ID_NUM, P.PROD_NAME, P.PROD_CATEGORY, 
CAST(P.PROD_LIST_PRICE-(S.AMOUNT_SOLD/S.QUANTITY_SOLD) AS DECIMAL(8,2)) AS DISCOUNT_PRICE_1, 
CAST(((S.AMOUNT_SOLD/S.QUANTITY_SOLD)*100)/P.PROD_LIST_PRICE AS DECIMAL(8,2)) AS 
DISCOUNT_RATE_2, DATEDIFF (DAY, S.SALE_DATE, S.PAYMENT_DATE) AS DAYS_TO_PAY_D 
  
FROM 
LI_PRODUCTS P, LI_CUSTOMERS_INTX CI, LI_SALES_12_13_14 S (this Sales table will be comprised of all orders) 
  
WHERE 
S.PROD_ID  = P.PROD_ID AND S.CUST_ID = CI.CUST_ID 
  
GROUP BY 
CI.CUST_ID, CI.CUST_FIRST_NAME+' '+CI.CUST_LAST_NAME, CI.CUST_MAIN_PHONE_NUMBER, 
CI.CUST_EMAIL, CI.CUST_POSTAL_CODE, P.PROD_ID, P.PROD_NAME, P.PROD_CATEGORY, CAST 
(P.PROD_LIST_PRICE-(S.AMOUNT_SOLD/S.QUANTITY_SOLD) AS DECIMAL(8,2)), CAST(((S.AMOUNT_SOLD/ 
S.QUANTITY_SOLD)*100)/P.PROD_LIST_PRICE AS DECIMAL(8,2)), DATEDIFF (DAY, S.SALE_DATE, 
S.PAYMENT_DATE) 
  
ORDER BY 
CI.CUST_ID DESC 


--BV03

CREATE VIEW PRODUCT_SOLD_GENDER WITH SCHEMABINDING
AS
SELECT
P.PROD_ID, P.PROD_NAME, P.PROD_DESC, P.PROD_SUBCATEGORY, P.PROD_CATEGORY, C.CUST_GENDER,
SUM(S.QUANTITY_SOLD) AS TOTAL_SOLD
FROM
[dbo].[FP_SALES] AS S
JOIN [dbo].[FP_PRODUCTS] AS P ON S.PROD_ID= P.PROD_ID
JOIN [dbo].[FP_CUSTOMERS] AS C ON S.CUST_ID= C.CUST_ID
GROUP BY
P.PROD_ID, P.PROD_NAME, P.PROD_DESC, P.PROD_SUBCATEGORY, P.PROD_CATEGORY,C.CUST_GENDER

SELECT * FROM PRODUCT_SOLD_GENDER
  

CREATE PROC PRODUCT_GENDER_SOLD 
( 
  @CUST_GENDER  NVARCHAR(2) 
) 
  
AS 
BEGIN 
SELECT 
P.PROD_ID, P.PROD_NAME, P.PROD_SUBCATEGORY, P.PROD_CATEGORY, C.CUST_GENDER,
CAST (SUM(QUANTITY_SOLD) AS decimal(10,2)) AS TOTAL_SOLD 
FROM  
FP_SALES AS S 
JOIN FP_PRODUCTS AS P ON  S.PROD_ID=P. PROD_ID 
JOIN FP_CUSTOMERS AS C ON S. CUST_ID =C. CUST_ID  
WHERE CUST_GENDER  = @CUST_GENDER
  
GROUP BY  
P.PROD_ID, P.PROD_NAME, P.PROD_SUBCATEGORY, P.PROD_CATEGORY, C.CUST_GENDER

END;

EXECUTE PRODUCT_GENDER_SOLD  ‘F’


PROC_BY_VIEW
CREATE PROC VW_PRODUCT_GENDER_SOLD 
( 
  @CUST_GENDER  NVARCHAR(2) 
) 
AS 
BEGIN 
SELECT 
PROD_ID, PROD_NAME, PROD_SUBCATEGORY, PROD_CATEGORY, CUST_GENDER, TOTAL_SOLD 
FROM PRODUCT_SOLD_GENDER 
WHERE CUST_GENDER = @CUST_GENDER
  
END;


--BV04

CREATE VIEW PRODUCT_SOLD_CATEGORY WITH SCHEMABINDING
AS
SELECT
P.PROD_ID, P.PROD_NAME, P.PROD_CATEGORY,COUN.COUNTRY_NAME,COUN.COUNTRY_REGION,
SUM(S.QUANTITY_SOLD) AS TOTAL_SOLD
FROM
[dbo].[FP_SALES] AS S
JOIN [dbo].[FP_PRODUCTS] AS P ON S.PROD_ID= P.PROD_ID
JOIN [dbo].[FP_CUSTOMERS] AS C ON S.CUST_ID= C.CUST_ID
JOIN [dbo].[FP_COUNTRY] AS COUN ON C.COUNTRY_ID=COUN.COUNTRY_ID

GROUP BY
P.PROD_ID, P.PROD_NAME, P.PROD_CATEGORY, COUN.COUNTRY_NAME, COUN.COUNTRY_REGION


CREATE PROC PRODUCT_COUNTER_REGION_SOLD 
( 
  @COUNTER_REGION  NVARCHAR(50) 
) 
  
AS 
BEGIN 
SELECT 
P.PROD_ID, P.PROD_NAME, P.PROD_SUBCATEGORY, P.PROD_CATEGORY, COUN.COUNTRY_NAME, COUN.COUNTRY_REGION,
CAST (SUM(QUANTITY_SOLD) AS decimal(10,2)) AS TOTAL_SOLD 
FROM  
FP_SALES AS S 
JOIN  FP_PRODUCTS AS P ON  S.PROD_ID=P. PROD_ID 
JOIN FP_CUSTOMERS AS C ON S. CUST_ID =C. CUST_ID  
JOIN FP_COUNTER AS COUN ON COUN.COUNTRY_ID =C.COUNTRY_ID 
WHERE COUN.COUNTRY_REGION =@ COUNTER_REGION   
GROUP BY  
P.PROD_ID, P.PROD_NAME, P.PROD_SUBCATEGORY, P.PROD_CATEGORY, COUN.COUNTRY_REGION
END;

EXECUTE PRODUCT_ COUNTER_REGION_SOLD  ‘Europe’


PROC_BY_VIEW
CREATE PROC VW_PRODUCT_COUNTER_REGION_SOLD 
( 
  @COUNTER_REGION  NVARCHAR(50) 
) 
AS 
BEGIN 
SELECT 
PROD_ID,PROD_NAME,PROD_CATEGORY, COUNTRY_NAME, COUNTRY_REGION, TOTAL_SOLD 
FROM  
PRODUCT_SOLD_CATEGORY
WHERE COUNTRY_REGION =@COUNTER_REGION   

END;


EXECUTE VW_PRODUCT_COUNTER_REGION_SOLD  'Europe'
