CREATE VIEW PRODUCT_SOLD_CATEGORY WITH SCHEMABINDING
AS
SELECT
P.PROD_ID, P.PROD_NAME, P.PROD_CATEGORY,COUN.COUNTRY_NAME,COUN.COUNTRY_REGION,
SUM(S.QUANTITY_SOLD) AS TOTAL_SOLD
FROM
[dbo].[FP_SALES] AS S
JOIN [dbo].[FP_PRODUCTS] AS P ON S.PROD_ID= P.PROD_ID
JOIN [dbo].[FP_CUSTOMERS] AS C ON S.CUST_ID= C.CUST_ID
JOIN [dbo].[FP_COUNTRY] AS COUN ON C.COUNTRY_ID=COUN.COUNTRY_ID

GROUP BY
P.PROD_ID, P.PROD_NAME, P.PROD_CATEGORY, COUN.COUNTRY_NAME, COUN.COUNTRY_REGION

SELECT * FROM PRODUCT_SOLD_CATEGORY

CREATE PROC VW_PRODUCT_COUNTER_REGION_SOLD 
( 
  @COUNTER_REGION  NVARCHAR(50) 
) 
AS 
BEGIN 
SELECT 
PROD_ID,PROD_NAME,PROD_CATEGORY, COUNTRY_NAME, COUNTRY_REGION, TOTAL_SOLD 
FROM  
PRODUCT_SOLD_CATEGORY
WHERE COUNTRY_REGION =@COUNTER_REGION   

END;


EXECUTE VW_PRODUCT_COUNTER_REGION_SOLD  'Europe'
